apiVersion: v1
kind: Secret
metadata:
  name: model-storage-config
  namespace: {{ .Values.main.namespace }}
  labels:
    app.kubernetes.io/component: ai-ml-workbench
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | quote }}
  AWS_S3_ENDPOINT: {{ .Values.storage.s3.endpoint | quote }}
  AWS_S3_BUCKET: {{ .Values.storage.s3.bucket | quote }}