---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-operator

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  # Note: operatorconfig.yaml should be applied AFTER the operator is installed
  # It will be applied separately in the installation script

commonLabels:
  app.kubernetes.io/name: external-secrets-operator
  app.kubernetes.io/part-of: openshift-aiops-platform
  app.kubernetes.io/managed-by: kustomize
