apiVersion: v1
kind: Namespace
metadata:
  name: jupyter-notebook-validator-operator
  labels:
    app.kubernetes.io/name: jupyter-notebook-validator-operator
    app.kubernetes.io/component: operator
    control-plane: controller-manager
