apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-notebook-validator-runner
  namespace: jupyter-notebook-validator-operator
  labels:
    app.kubernetes.io/name: jupyter-notebook-validator-operator
    app.kubernetes.io/component: validation-runner
